include "dependencies.lua"

require("vstudio")

local vs = premake.vstudio.vc2010

local function premakeVersionComment(prj)
	premake.w('<!-- Generated by Premake ' .. _PREMAKE_VERSION .. ' -->')
end

local function vcpkg(prj)
	premake.w('<VcpkgTriplet Condition="\'$(Platform)\'==\'x64\'">x64-windows-static</VcpkgTriplet>')
	premake.w('<VcpkgEnabled>false</VcpkgEnabled>')
end

premake.override(premake.vstudio.vc2010.elements, "project", function(base, prj)
	local calls = base(prj)
	table.insertafter(calls, vs.xmlDeclaration, premakeVersionComment)
	return calls
end)

premake.override(premake.vstudio.vc2010.elements, "globals", function(base, prj)
	local calls = base(prj)
	table.insertafter(calls, vs.globals, vcpkg)
	return calls
end)

InstallTensorFlowLib()

workspace "Sandbox"
	architecture "x64"
	configurations
	{
		"Debug",
		"Release"
	}
	
	startproject "SimpleAddModel"

outputdir = "%{cfg.system}-%{cfg.buildcfg}-%{cfg.architecture}"

group ""
	include "TFModelCore"
	include "SimpleAddModel"
	include "LinearRegressionModel"
	include "ClassifierModel"
	include "TrainingLinearRegressionModel"
	include "TrainingClassifierModel"
group ""


